/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

 // Markus
 // Elisa
 // Guest User (Paulo S.)
 // Tuco
 // Henrique
package pokepo

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals

class BatalhaTest {
    /*@Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    } */
    @Test fun batalha_entre_squirtle_e_charmander_vence_squirtle(){
        val jogador1 = "squirtle"
        val jogador2 = "charmander"

        val vencedor = batalha(jogador1, jogador2)

        assertEquals(vencedor, jogador1)
    }
    @Test fun batalha_entre_squirtle_e_bulbassauro_vence_bulbassauro(){
        val jogador1 = "squirtle"
        val jogador2 = "bulbassauro"

        val vencedor = batalha(jogador1, jogador2)

        assertEquals(vencedor, jogador2)
    }
    @Test fun batalha_entre_charmander_e_bulbassauro_vence_charmander(){
        val jogador1 = "charmander"
        val jogador2 = "bulbassauro"

        val vencedor = batalha(jogador1, jogador2)
        assertEquals(vencedor, jogador1)
    }
    @Test fun batalha_entre_charmander_e_squirtle_vence_squirtle(){
        val jogador1 = "charmander"
        val jogador2 = "squirtle"

        val vencedor = batalha(jogador1, jogador2)
        assertEquals(vencedor, jogador2)
    }
    @Test fun batalha_entre_bulbassauro_e_charmander_vence_charmander(){
        val jogador1 = "bulbassauro"
        val jogador2 = "charmander"

        val vencedor = batalha(jogador1, jogador2)
        assertEquals(vencedor, jogador2)
    }
    @Test fun batalha_entre_bulbasauro_e_squirtle_vence_bulbassauro(){
        val jogador1 = "bulbassauro"
        val jogador2 = "squirtle"

        val vencedor = batalha(jogador1, jogador2)
        assertEquals(vencedor, jogador1)
    }
    @Test fun batalha_entre_squirtle_e_squirtle_vence_squirtle(){
        val jogador1 = "squirtle"
        val jogador2 = "squirtle"

        val vencedor = batalha(jogador1, jogador2)
        assertEquals(vencedor, jogador1)
    }
    @Test fun batalha_entre_bulbassauro_e_bulbassauro_vence_bulbassauro(){
        val jogador1 = "bulbassauro"
        val jogador2 = "bulbassauro"

        val vencedor = batalha(jogador1, jogador2)
        assertEquals(vencedor, jogador1)
    }
    @Test fun batalha_entre_charmander_e_charmander_vence_charmander(){
        val jogador1 = "charmander"
        val jogador2 = "charmander"

        val vencedor = batalha(jogador1, jogador2)
        assertEquals(vencedor, jogador1)
    }
}
