/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pokepo
import pokepo.Pokemon.BULBASSAURO
import pokepo.Pokemon.SQUIRTLE
import pokepo.Pokemon.CHARMANDER

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals
import kotlin.test.assertNull

class BatalhaTest {
    /*@Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    } */
    @Test fun batalha_entre_squirtle_e_charmander_vence_squirtle(){
        val jogador1 = SQUIRTLE
        val jogador2 = CHARMANDER

        val vencedor = batalha(jogador1, jogador2)

        assertEquals(vencedor, jogador1)
    }
    @Test fun batalha_entre_squirtle_e_bulbassauro_vence_bulbassauro(){
        val jogador1 = SQUIRTLE
        val jogador2 = BULBASSAURO

        val vencedor = batalha(jogador1, jogador2)

        assertEquals(vencedor, jogador2)
    }
    @Test fun batalha_entre_charmander_e_bulbassauro_vence_charmander(){
        val jogador1 = CHARMANDER
        val jogador2 = BULBASSAURO

        val vencedor = batalha(jogador1, jogador2)
        assertEquals(vencedor, jogador1)
    }
    @Test fun batalha_entre_charmander_e_squirtle_vence_squirtle(){
        val jogador1 = CHARMANDER
        val jogador2 = SQUIRTLE

        val vencedor = batalha(jogador1, jogador2)
        assertEquals(vencedor, jogador2)
    }
    @Test fun batalha_entre_bulbassauro_e_charmander_vence_charmander(){
        val jogador1 = BULBASSAURO
        val jogador2 = CHARMANDER

        val vencedor = batalha(jogador1, jogador2)
        assertEquals(vencedor, jogador2)
    }
    @Test fun batalha_entre_bulbasauro_e_squirtle_vence_bulbassauro(){
        val jogador1 = BULBASSAURO
        val jogador2 = SQUIRTLE

        val vencedor = batalha(jogador1, jogador2)
        assertEquals(vencedor, jogador1)
    }
    @Test fun batalha_entre_squirtle_e_squirtle_empate(){
        val jogador1 = SQUIRTLE
        val jogador2 = SQUIRTLE

        val vencedor = batalha(jogador1, jogador2)
        assertNull(vencedor)
    }
    @Test fun batalha_entre_bulbassauro_e_bulbassauro_empate(){
        val jogador1 = BULBASSAURO
        val jogador2 = BULBASSAURO

        val vencedor = batalha(jogador1, jogador2)
        assertNull(vencedor)
    }
    @Test fun batalha_entre_charmander_e_charmander_empate(){
        val jogador1 = CHARMANDER
        val jogador2 = CHARMANDER

        val vencedor = batalha(jogador1, jogador2)
        assertNull(vencedor)
    }
}
